# Generated by Django 4.1.5 on 2023-02-04 00:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='code',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='invitees', to=settings.AUTH_USER_MODEL),
        ),
    ]
