# Generated by Django 4.1.5 on 2023-02-04 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_alter_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
